version: "0.2"
allowCompoundWords: true
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
    scope: null
dictionaries:
  - custom-dictionary
words: []
ignoreWords: []
import: []
